language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
before_install:
  - "sudo apt-get update"
  - "sudo apt-get install xtrace ghc cabal-install xcb-proto happy alex parallel"
  - "cabal update"
  - "sh -e /etc/init.d/xvfb start"
  - "xtrace -D:98 -d:99 -k -n &"
  - "export DISPLAY=:98.0"
install:
  - "git clone https://github.com/tych0/xcb-types.git"
  - "cd xcb-types"
  - "cabal install"
  - "cd .."
  - "git clone https://github.com/tych0/xcffib.git"
  - "cd xcffib"
  - "cabal install --only-dependencies"
  - "cabal configure"
  - "pip install -r requirements.txt"
  - "make xcffib"
  - "pip install ."
  - "cd .."
  - "pip install ."
script: "py.test"
