language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
before_install:
  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
  #- "sudo apt-get update"
  #- "sudo apt-get install xtrace"
  #- "xtrace -D:98 -d:99 -k -n -w &"
  #- "export DISPLAY=:98.0"
install:
  - "pip install xcffib"
  - "pip install ."
  - sudo apt-get install xtrace
script: "xtrace -n py.test"
