language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
before_install:
  - "sudo apt-get update"
  - "sudo apt-get install xtrace"
  - "sh -e /etc/init.d/xvfb start"
  - "xtrace -D:98 -d:99 -k -n &"
  - "export DISPLAY=:98.0"
install:
  - "pip install xcffib"
  - "pip install ."
script: "py.test"
